grails-app/domain/fr/itu/mbds/grails/Annonce.groovy
package fr.itu.mbds.grails

class Annonce {

    String      title
    String      description
    Float       price
    Boolean     status = Boolean.FALSE
    Date        dateCreated
    Date        lastUpdated
    List        illustrations

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title nullable: false, blank: false
        description nullable: false, blank: false
        price min: 0F, nullable: false
        status nullable: false
    }

    static mapping = {
        description type: 'text'
    }
}

grails-app/controllers/fr/itu/mbds/grails/AnnonceController.groovy
package fr.itu.mbds.grails

import grails.plugin.springsecurity.annotation.Authorities
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.springframework.web.multipart.MultipartFile
import org.springframework.web.multipart.MultipartHttpServletRequest
import org.springframework.web.multipart.commons.CommonsMultipartFile
import org.springframework.web.multipart.support.StandardMultipartHttpServletRequest
import org.springframework.web.servlet.ModelAndView

import javax.servlet.http.Part

import static org.springframework.http.HttpStatus.*


@Secured(['ROLE_ADMIN','ROLE_MODO'])
class AnnonceController {

    AnnonceService annonceService
    UserService userService
    IllustrationService illustrationService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond annonceService.list(params), model:[annonceCount: annonceService.count()]
    }

    def show(Long id) {
        respond annonceService.get(id)
    }

    def create() {
        params.author = userService.list()
        respond new Annonce(params)
    }

    def save(Annonce annonce ) {
        if (annonce == null) {
            notFound()
            return
        }

        try {
           def newAnnonce =  annonceService.save(annonce)
           def imageList = request.getMultiFileMap().get("illustration[]").toList()
            //get upload path
           def path  = grailsApplication.config.getProperty('illustrations.path')
            //upload file
           imageList.each{
                item ->
                    def obj = item
                    obj.transferTo(new File(path+""+obj.filename))
                    def illustration = new Illustration("filename" : obj.filename,"annonce" : newAnnonce.getId())
                    illustrationService.save(illustration)
            }
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }

    def edit(Long id) {
        return new ModelAndView("/annonce/edit", [annonce: annonceService.get(id), user:  userService.list()])
    }

    def update(Annonce annonce ) {
         //annonce.price = (int) annonce.price
        if (annonce == null) {
            notFound()
            return
        }
        def path  = grailsApplication.config.getProperty('illustrations.path')
        List<Part> parts = new ArrayList<Part>()
        List<Object> names = new ArrayList< >()
        //get file from view
        for(int i = 0 ; i< annonce.illustrations.size();i++){
            parts.add( request.getPart("ill"+i))
            names.add( request.getPart("ill"+i).fileItem.name)
        }
        //modification des anciennes illustrations
       for(int i = 0 ; i< annonce.illustrations.size();i++){
            def illustration = annonce.illustrations.get(i)
            if(parts.get(i).fileItem.name.isEmpty() == false ||  parts.get(i).fileItem.name.length()!= 0){
                def myObj = new  StandardMultipartHttpServletRequest.StandardMultipartFile(parts.get(i),parts.get(i).fileItem.name)
                //telechargement du fichier
                myObj.transferTo(new File(path+""+myObj.filename))
                illustration.filename = myObj.filename
                illustrationService.save(illustration)
            }
        }

        //nouvelle illustration
        def nbrOfNewImg = java.lang.Integer.parseInt(params.get("nombreNouvelleImage"))


        for(int i = 0 ; i< nbrOfNewImg ; i++){
            def part = request.getPart("newImg"+i)
            def myObj = new  StandardMultipartHttpServletRequest.StandardMultipartFile(part,part.fileItem.name)
            myObj.transferTo(new File(path+""+myObj.filename))
            def illustration = new Illustration("filename" : myObj.filename,"annonce" : annonce.getId())
            illustrationService.save(illustration)
        }


        try {
            annonceService.save(annonce)
        } catch (ValidationException e) {
            //respond annonce.errors , annonce: annonceService.get(annonce.getId()), user:  userService.list(), view:'edit'
            return new ModelAndView("/annonce/edit", [ erros : annonce.errors,annonce: annonceService.get(annonce.getId()), user:  userService.list()])
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        annonceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />

        <asset:javascript src="myFunction.js" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <!--<div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-annonce" class="content scaffold-create" role="main">

            <g:form resource="${this.annonce}" method="POST">
                <fieldset class="form">
                    <f:all bean="${annonce}"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
-->
    <div class="row offset-2 col-sm-8 ">
        <h1><g:message code="default.create.label" args="[entityName]" /></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${this.annonce}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.annonce}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>
        <div class="col-12">
            <form action="/annonce/save" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="entrer le titre">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <input type="text" class="form-control" id="description" name="description" placeholder="entrer la description">
                </div>
                <div class="form-group">
                    <label for="price">Prix</label>
                    <input type="number decimal"  class="form-control" id="price" name="price" placeholder="entrer le prix">
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input type="hidden" name="_status" />
                        <input type="checkbox" name="status" class="form-check-input" id="status"  />
                        <label class="form-check-label" for="status">
                            Status
                        </label>
                    </div>
                </div>
                <div class="pImage">
                    <label>Illustration</label>
                    <button  onclick="addimg()"  type="button" style="background:none; border:none"><i class="fa fa-plus-square"></i></button>

                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">upload file</div>
                        </div>
                        <input type="file" name="illustration[]" class="form-control"  >
                        <button onclick="removeimg(this)"  type="button" style="background:none; color:red;border:none"><i class="fa fa-minus-square"></i></button>
                    </div>

                </div>

                <div class="mt-2">
                    <label for="author">Author</label>
                    <select class="form-control " name="author.id"id="author" >
                        <g:each in="${params.author}" var="auth">
                            <option value="${auth.id}">${auth.username}</option>
                        </g:each>
                    </select>
                </div>

                <g:submitButton name="create" class="btn btn-primary save mt-2" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            </form>
        </div>

    </div>
    </body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="col-12">
        <h1><g:message code="default.list.label" args="[entityName]" /></h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <table class="table table-bordered" collection="${annonceList}">
            <thead>
            <tr>
                <g:sortableColumn property="title" title="Title" />
                <g:sortableColumn property="description" title="Description" />
                <g:sortableColumn property="price" title="Price" />
                <g:sortableColumn property="status" title="Status" />
                <g:sortableColumn property="illustrations" title="Illustration" />
                <g:sortableColumn property="author" title="Author" />

                <th>*</th>
            </tr>
            </thead>
            <tbody>
            <g:each in="${annonceList}" var="annonce">
                <tr>
                    <td>${annonce.title}</td>
                    <td>${annonce.description}</td>
                    <td>${annonce.price}</td>
                    <td>${annonce.status}</td>
                    <td>
                        <g:each in="${annonce.illustrations}" var="illustration">
                            <img src="${resource(dir: 'images', file: "${illustration.filename}")}">
                        </g:each>
                    </td>
                    <td>${annonce.author.username}</td>
                    <td> <a href="/annonce/edit/${annonce.id}" class="fas fa-edit"></a>
                        <a href="/annonce/show/${annonce.id}" class="fas fa-info-circle"></a></td>
                </tr>
            </g:each>
            </tbody>
        </table>
        <div class="pagination">
            <g:paginate total="${annonceCount ?: 0}" />
        </div>
    </div>
    </body>
</html>

grails-app/views/annonce/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>

    <h1><g:message code="default.show.label" args="[entityName]" /></h1>
    <div class="col-12">
            <div class="form-group">
                <label for="title">Title</label>
                <input readonly type="text" class="form-control" value="${this.annonce.title}" name="title" id="title" placeholder="entrer le titre">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input readonly type="text" class="form-control" value="${this.annonce.description}" id="description" name="description" placeholder="entrer la description">
            </div>
            <div class="form-group">
                <label for="price">Prix</label>
                <input readonly type="number decimal"   class="form-control" value="${this.annonce.price.toString().replace('.',',')}" id="price" name="price" placeholder="entrer le prix">
            </div>
            <div class="form-group">
                <div class="form-check">
                    <input readonly type="hidden" name="_status" />
                    <g:if test="${this.annonce.status == false}">
                        <input readonly type="checkbox" name="status" class="form-check-input" value="${this.annonce.status}"  id="status"  />
                    </g:if>
                    <g:else>
                        <input readonly type="checkbox" name="status" class="form-check-input" checked="checked"  id="status"  />
                    </g:else>
                    <label class="form-check-label" for="status">
                        Status
                    </label>
                </div>
            </div>

            <div id="illustrationList">
                <g:each in="${this.annonce.illustrations}" var="illustration">
                    <img src="${resource(dir: 'images', file: "${illustration.filename}")}">
                </g:each>

            </div>

            <div class="mt-2">
                <label for="author">Author</label>
                <input readonly type="text"   class="form-control" value="${this.annonce.author.username}" id="author" name="author" placeholder="">
            </div>

        <g:form resource="${this.annonce}" method="DELETE">
            <fieldset class="buttons">
                <g:link class="edit" action="edit" resource="${this.annonce}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <input class="btn btn-primary save mt-2 " type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </fieldset>
        </g:form>
    </div>
    </body>
</html>