grails-app/domain/fr/itu/mbds/grails/User.groovy
package fr.itu.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/fr/itu/mbds/grails/UserController.groovy
package fr.itu.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import org.springframework.web.servlet.ModelAndView

import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN','ROLE_MODO'])
class UserController {

    UserService userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model:[userCount: userService.count()]
    }

    def show(Long id) {
        respond userService.get(id)
    }

    def create() {
        respond new User(params)
    }

    def save(User user,int role) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
            def roles = Role.get(role)
            UserRole.create(user, roles, true)
        } catch (ValidationException e) {
            respond user.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    def edit(Long id) {
        //respond userService.get(id)
        //render(view:'/user/edit',model:[children:userService.get(id)])

        return new ModelAndView("/user/edit", [user: userService.get(id) ])
    }

    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*'{ respond user, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        userService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
    <div class="row offset-2 col-sm-8" >
        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>

            <div class="col-sm-12" >
                <form action="/user/save" method="post">

                    <div class="form-group">
                        <label for="inputUsername">Username*</label>
                        <input type="text" class="form-control" id="inputUsername" name="username" placeholder="votre nom">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword">Password*</label>
                        <input type="text" class="form-control" name="password" id="inputPassword" placeholder="votre mot de passe">
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input type="hidden" name="_passwordExpired" />

                            <input type="checkbox" name="passwordExpired" class="form-check-input" id="passwordExpired"  />
                            <label class="form-check-label" for="passwordExpired">
                                Password Expired
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-check">
                            <input type="hidden" name="_accountLocked" />
                            <input type="checkbox" name="accountLocked" class="form-check-input" id="accountLocked"  />
                            <label class="form-check-label" for="passwordExpired">
                                Account Locked
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-check">
                            <input type="hidden" name="_accountExpired" />
                            <input type="checkbox" name="accountExpired" class="form-check-input" id="accountExpired"  />
                            <label class="form-check-label" for="accountExpired">
                                Password Expired
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="form-check">
                            <input type="hidden" name="_enabled" />
                            <input type="checkbox" name="enabled" checked="checked" class="form-check-input" id="enabled"  />
                            <label class="form-check-label" for="enabled">
                                Enabled
                            </label>
                        </div>
                    </div>
                     <div class="col-sm-4 mb-2">
                        <label class="form-check-label" for="role">Role </label>
                        <select class="custom-select" id="role" name="role">
                            <option value="1">ROLE_ADMIN</option>
                            <option value="2">ROLE_MODO</option>
                            <option value="3">ROLE_CLIENT</option>
                        </select>
                    </div>
                    <g:submitButton name="create" class="btn btn-primary save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </form>
            </div>
    </div>
</body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
    <!--
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-user" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="PUT">
                <g:hiddenField name="version" value="${this.user?.version}" />
                <fieldset class="form">
                    <f:all bean="user"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    -->
    <div class="row offset-2 col-sm-8" >
    <!--<div>
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
        </div>
        -->

        <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>

        <div class="col-sm-12" >
            <form action="/user/update/${user.id}" method="post">
                <input type="hidden" name="_method" value="PUT" id="_method" />
                <input type="hidden" name="version" value="${user.version.value}" id="version" />
                <div class="form-group">
                    <label for="inputPassword">Password*</label>
                    <input type="text" class="form-control" name="password" value="${user.password}" id="inputPassword" placeholder="votre mot de passe">
                </div>
                <div class="form-group">
                    <label for="inputUsername">Username*</label>
                    <input type="text" class="form-control" id="inputUsername" name="username" value="${user.username}" placeholder="votre nom">
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <input type="hidden" name="_passwordExpired" />
                        <g:if test="${user.passwordExpired == true}">
                            <input type="checkbox" name="passwordExpired"   checked="checked" class="form-check-input" id="passwordExpired"  />
                        </g:if>
                        <g:else>
                            <input type="checkbox" name="passwordExpired"   class="form-check-input" id="passwordExpired"  />
                        </g:else>
                        <label class="form-check-label" for="passwordExpired">
                            Password Expired
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <input type="hidden" name="_accountLocked" />
                        <g:if test="${user.accountLocked == true}">
                            <input type="checkbox" name="accountLocked"   checked="checked" class="form-check-input" id="accountLocked"  />
                        </g:if>
                        <g:else>
                            <input type="checkbox" name="accountLocked"      class="form-check-input" id="accountLocked"  />
                        </g:else>
                        <label class="form-check-label" for="passwordExpired">
                            Account Locked
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <input type="hidden" name="_accountExpired" />
                        <g:if test="${user.accountExpired == true}">
                            <input type="checkbox" name="accountExpired"  checked="checked" class="form-check-input" id="accountExpired"  />
                        </g:if>
                        <g:else>
                            <input type="checkbox" name="accountExpired"   class="form-check-input" id="accountExpired"  />
                        </g:else>
                        <label class="form-check-label" for="accountExpired">
                            Password Expired
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <input type="hidden" name="_enabled" />
                        <g:if test="${user.enabled == true}">
                            <input type="checkbox" name="enabled" checked="checked" class="form-check-input" id="enabled"  />
                        </g:if>
                        <g:else>
                            <input type="checkbox" name="enabled"  class="form-check-input" id="enabled"  />
                        </g:else>
                        <label class="form-check-label" for="enabled">
                            Enabled
                        </label>
                    </div>
                </div>
                <input class="save btn btn-outline-primary" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
            </form>
        </div>
    </div>
    </body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
<!--
       <div class="nav" role="navigation">
            <ul>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-user" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table class="test" collection="${userList}" except="['password']" />

            <div class="pagination">
                <g:paginate total="${userCount ?: 0}" />
            </div>
        </div>
-->
    <div class="row">
        <div class="col-md-12">
            <h1>Liste des utilisateurs de <b>Lecoincoin</b></h1>
            <table class="table table-bordered" collection="${userList}">
                <thead>
                <tr>
                    <g:sortableColumn property="id" title="id" />
                    <g:sortableColumn property="username" title="username" />
                    <g:sortableColumn property="passwordExpired" title="Password Expired" />
                    <g:sortableColumn property="accountLocked" title="Account Locked" />
                    <g:sortableColumn property="accountExpired" title="Account Expired" />
                    <g:sortableColumn property="enabled" title="Enabled" />
                    <th>*</th>
                </tr>
                </thead>
                <tbody>
                 <g:each in="${userList}" var="user">
                     <tr>
                         <td>${user.id}</td>
                         <td>${user.username}</td>
                         <td>${user.passwordExpired}</td>
                         <td>${user.accountLocked}</td>
                         <td>${user.accountExpired}</td>
                         <td>${user.enabled}</td>
                         <td><a href="/user/edit/${user.id}" class="badge badge-primary">Edit</a>
                             <a href="/user/show/${user.id}" class="badge badge-secondary">Show detail</a></td>
                     </tr>
                 </g:each>
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <g:paginate total="${userCount ?: 0}" />
                </ul>
            </nav>

        </div>
    </div>
    </body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>

        <h1><g:message code="default.show.label" args="[entityName]" /></h1>
        <div class="form-group">
            <label for="inputPassword">Password*</label>
            <input readonly type="text" class="form-control" name="password" value="${user.password}" id="inputPassword" placeholder="votre mot de passe">
        </div>
        <div class="form-group">
            <label for="inputUsername">Username*</label>
            <input readonly type="text" class="form-control" id="inputUsername" name="username" value="${user.username}" placeholder="votre nom">
        </div>

        <div class="form-group">
            <div class="form-check">
                <input readonly type="hidden" name="_passwordExpired" />
                <g:if test="${user.passwordExpired == true}">
                    <input readonly type="checkbox" name="passwordExpired"   checked="checked" class="form-check-input" id="passwordExpired"  />
                </g:if>
                <g:else>
                    <input readonly type="checkbox" name="passwordExpired"   class="form-check-input" id="passwordExpired"  />
                </g:else>
                <label class="form-check-label" for="passwordExpired">
                    Password Expired
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="form-check">
                <input readonly type="hidden" name="_accountLocked" />
                <g:if test="${user.accountLocked == true}">
                    <input readonly type="checkbox" name="accountLocked"   checked="checked" class="form-check-input" id="accountLocked"  />
                </g:if>
                <g:else>
                    <input readonly type="checkbox" name="accountLocked"      class="form-check-input" id="accountLocked"  />
                </g:else>
                <label class="form-check-label" for="passwordExpired">
                    Account Locked
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="form-check">
                <input readonly type="hidden" name="_accountExpired" />
                <g:if test="${user.accountExpired == true}">
                    <input readonly type="checkbox" name="accountExpired"  checked="checked" class="form-check-input" id="accountExpired"  />
                </g:if>
                <g:else>
                    <input readonly type="checkbox" name="accountExpired"   class="form-check-input" id="accountExpired"  />
                </g:else>
                <label class="form-check-label" for="accountExpired">
                    Password Expired
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="form-check">
                <input readonly type="hidden" name="_enabled" />
                <g:if test="${user.enabled == true}">
                    <input readonly type="checkbox" name="enabled" checked="checked" class="form-check-input" id="enabled"  />
                </g:if>
                <g:else>
                    <input readonly type="checkbox" name="enabled"  class="form-check-input" id="enabled"  />
                </g:else>
                <label class="form-check-label" for="enabled">
                    Enabled
                </label>
            </div>
        </div>
        <g:form resource="${this.user}" method="DELETE">
            <fieldset class="buttons">
                <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                <input class="btn btn-primary save mt-2 " type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </fieldset>
        </g:form>
    </body>
</html>